#!/usr/bin/env python3

import os

from ament_index_python.packages import get_package_share_directory
from launch import LaunchDescription
from launch.actions import DeclareLaunchArgument, ExecuteProcess, IncludeLaunchDescription
from launch.conditions import IfCondition
from launch.launch_description_sources import PythonLaunchDescriptionSource
from launch.substitutions import LaunchConfiguration
from launch_ros.actions import Node


def generate_launch_description():
    ifc_share = get_package_share_directory("ifc2pointcloud")
    gazebo_ros_share = get_package_share_directory("gazebo_ros")

    # Pass your generated world path with world:=... when launching.
    default_world = os.path.join(ifc_share, "world", "Example_PCD.sdf")
    default_robot_sdf = os.path.join(ifc_share, "models", "scan_robot.sdf")

    world = LaunchConfiguration("world")
    robot_sdf = LaunchConfiguration("robot_sdf")
    spawn_robot = LaunchConfiguration("spawn_robot")
    auto_drive = LaunchConfiguration("auto_drive")

    return LaunchDescription([
        DeclareLaunchArgument(
            "world",
            default_value=default_world,
            description="Gazebo world file path (generated by sdf_builder).",
        ),
        DeclareLaunchArgument(
            "robot_sdf",
            default_value=default_robot_sdf,
            description="SDF model path for local scan robot.",
        ),
        DeclareLaunchArgument(
            "spawn_robot",
            default_value="true",
            description="Spawn the scan robot model into Gazebo.",
        ),
        DeclareLaunchArgument(
            "auto_drive",
            default_value="true",
            description="Publish constant cmd_vel for autonomous scan coverage.",
        ),

        IncludeLaunchDescription(
            PythonLaunchDescriptionSource(
                os.path.join(gazebo_ros_share, "launch", "gzserver.launch.py")
            ),
            launch_arguments={"world": world}.items(),
        ),
        IncludeLaunchDescription(
            PythonLaunchDescriptionSource(
                os.path.join(gazebo_ros_share, "launch", "gzclient.launch.py")
            ),
        ),

        Node(
            package="gazebo_ros",
            executable="spawn_entity.py",
            output="screen",
            arguments=[
                "-entity", "scan_robot",
                "-file", robot_sdf,
                "-x", "0.0",
                "-y", "0.0",
                "-z", "0.2",
            ],
            condition=IfCondition(spawn_robot),
        ),

        ExecuteProcess(
            cmd=[
                "ros2",
                "topic",
                "pub",
                "-r",
                "5",
                "/cmd_vel",
                "geometry_msgs/msg/Twist",
                "{linear: {x: 0.8}, angular: {z: 0.25}}",
            ],
            output="screen",
            condition=IfCondition(auto_drive),
        ),
    ])
